spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          ddl-auto: update
  application:
    name: PAYMENTSERVICE
server:
  port: 2518